version: '3.9'

x-aphrc-common: &aphrc-common
  build:
    context: .
    dockerfile: Dockerfile
  volumes: &aphrc-common-volumes
    - ./:/code
  working_dir: /code
  environment: &aphrc-common-env
    REDIS_HOST: "aphrc-redis"
    REDIS_PORT: "6379"
    DEBUG: "True"

services:
  api:
    <<: *aphrc-common
    ports:
      - "8000:8000"
    command: sleep infinity
    container_name: api-standalone
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-api-standalone
    hostname: aphrc-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
